### ISSUE TITLE
How to reproduce the results of the paper

### ISSUE THREAD

**Issue by sean186** [skelemoa/tal-hmo#4]
Hello，I used `git clone --recursive https://github.com/skelemoa/tal-hmo`  and  I can't reproduce the paper.
The strange thing is how the code is the same with https://github.com/xlliu7/MUSES
I did not find any code that integrates with audio.
Is there a problem?
Looking forward to your reply

**Comment by wangqingxun50** [comment]
> 

I have the same question. Have you solved it？

**Comment by miccooper9** [comment]
Hello, thanks for your interest and questions. The repo is still incomplete. As for the similarity with Muses, because we modify existing approaches like Muses and GTAD by fusing audio, we reuse the existing architectures. We will upload the remaining files and clear instructions to run the code very soon.

**Comment by jazib-sudo** [comment]
Hey sorry for the late response,
You can download the best proposals for each dataset from tal-hmo/Best_proposals directory and replicate our results.
You can also perform all encoding fusion schemes by using: 
GTAD for DupTrim,AvgTrim, and Concat:
python gtad_fusion.py

MUSES for DupTrim,AvgTrim and Concat:
python muses_fusion.py

GTAD RMattn:
python models.py

Muses
python models_Muses.py

PGCN
python pgcn_models.py

**Comment by jazib-sudo** [comment]
I am not closing this issue yet, if you have any problems feel free to ask again.
I will close the issue in 7 days of no response.
